services:
  moidify:
    build: .
    container_name: moidify
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./music:/app/music
      - ./data:/app/data
      - ./covers:/app/covers
    environment:
      - MOIDIFY_MUSIC_DIR=/app/music
      - MOIDIFY_COVERS_DIR=/app/covers
      - MOIDIFY_DB_PATH=/app/data/music.db
